In [1]:
# importing numpy module
import numpy as np

In [2]:
# to convert a list into array

In [3]:
lst = [1,2,3,4,5]

In [4]:
# method 1
arr1a= np.array(lst)

In [5]:
arr1a

array([1, 2, 3, 4, 5])

In [6]:
type(arr1a)
# .ndarray n-dim array

numpy.ndarray

In [7]:
# method 2
arr1b = np.asarray(lst)

In [8]:
arr1b

array([1, 2, 3, 4, 5])

In [9]:
arr1a==arr1b

array([ True,  True,  True,  True,  True])

In [10]:
# to check dim
print(arr1a.ndim)
print(arr1b.ndim)

1
1


In [11]:
# method 3
arr1c=np.asanyarray(lst)

In [12]:
arr1c

array([1, 2, 3, 4, 5])

In [13]:
# 2-D array or Matrix

In [14]:
lst2=[[1,2,3],[9,8,7]]

In [15]:
arr2a = np.asanyarray(lst2)

In [16]:
arr2a

array([[1, 2, 3],
       [9, 8, 7]])

In [17]:
mat2a= np.matrix(lst2)

In [18]:
mat2a

matrix([[1, 2, 3],
        [9, 8, 7]])

In [19]:
type(arr2a)

numpy.ndarray

In [20]:
type(mat2a)

numpy.matrix

In [21]:
# solo-copy
a=arr2a

In [22]:
a

array([[1, 2, 3],
       [9, 8, 7]])

In [23]:
a[0][2]=100

In [24]:
a

array([[  1,   2, 100],
       [  9,   8,   7]])

In [25]:
arr2a

array([[  1,   2, 100],
       [  9,   8,   7]])

In [26]:
# observe that in solo-copy, 'a' and 'arr2a' are two alias of same address that's why change in one reflects in another. 

In [27]:
# deep-copy

In [28]:
b= np.copy(arr2a)

In [29]:
b

array([[  1,   2, 100],
       [  9,   8,   7]])

In [30]:
b[0][2]=3

In [31]:
b

array([[1, 2, 3],
       [9, 8, 7]])

In [32]:
arr2a

array([[  1,   2, 100],
       [  9,   8,   7]])

In [33]:
print(type(b))
print(type(arr2a))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [34]:
# observe in deep copy, var 'b' have separate memo add and copied the 'values' and 'type' from 'arr2a'

In [35]:
# to generate dataset or array using 'fromfunction()'

In [36]:
 np.fromfunction(lambda x,y : x==y , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [37]:
np.fromfunction(lambda x,y: x*y , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [38]:
# to form array using iterable
itr = (i+i for i in range(1,4))

In [39]:
np.fromiter(itr,'float')

array([2., 4., 6.])

In [40]:
# to generate arr using string
np.fromstring("1,2,3,4,5" , sep=',')
# we can also use space ' ' as a separator

array([1., 2., 3., 4., 5.])

In [41]:
# to find dim,shape(r*c),size(number_of_elements)
arr2a

array([[  1,   2, 100],
       [  9,   8,   7]])

In [42]:
arr2a.ndim

2

In [43]:
arr2a.shape

(2, 3)

In [44]:
arr2a.size

6

In [45]:
arr2a.dtype

dtype('int64')

In [46]:
# in numpy we can have arrays with decimal values
# numpy.arange(start,end,jump)

In [47]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
# Below code will result in error
#list(range(0.1,2.0))

In [49]:
np.arange(0.1,10.0)

array([0.1, 1.1, 2.1, 3.1, 4.1, 5.1, 6.1, 7.1, 8.1, 9.1])

In [50]:
np.arange(0.1,2.0, 0.2)

array([0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9])

In [51]:
list(np.arange(0.5,5.5,0.5))

[0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]

In [52]:
# The numpy.logspace() function returns number spaces evenly w.r.t interval on a log scale.
# numpy.logspace(start,stop,num_of_points_generated = 50, endpoint = True(by default ), base = 10.0, dtype = None)
np.logspace(1,10, 5, base=2)

array([   2.        ,    9.51365692,   45.254834  ,  215.2694823 ,
       1024.        ])

In [53]:
# The NumPy.linspace() function returns an array of evenly spaced values within the specified interval [start, stop].
# It is similar to NumPy.arange() function but instead of a step, it uses a sample number. 
np.linspace(1,5 , 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [54]:
# numpy.zeros

In [55]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [56]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
# it creates 3 matrices of 2*2 i.e. a 3-dim matrices
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [58]:
# it creates a 3*3 matrix having 2*2 matrix as an element i.e. a 4-dim matrix
np.zeros((3,3,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [59]:
# numpy.ones()  same as  numpy.zeros() but ends up creating an arr with '1' as an entry

In [60]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [61]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [62]:
# numpy.empty(shape, dtype = float, order = ‘C’) : Return a new array of given shape and type, with random values.
np.empty(5)

array([1., 1., 1., 1., 1.])

In [63]:
np.empty((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [64]:
np.empty((3,3)) + 5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [65]:
# to create an identiy matrix of order n
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
# np.random.rand() generates random numbers from a uniform distribution over [0, 1). 
# The values are all between 0 (inclusive) and 1 (exclusive).
np.random.rand(5)

array([0.02110711, 0.92627188, 0.18902152, 0.16306552, 0.68691049])

In [67]:
np.random.rand(3,3)

array([[0.63418658, 0.59614134, 0.97690227],
       [0.97943155, 0.21673733, 0.57718173],
       [0.28557321, 0.04605101, 0.57307101]])

In [68]:
# creates a 4*4 matix with random values from 1 to 10
np.random.randint(1,10, (4,4))

array([[6, 1, 5, 1],
       [2, 6, 4, 1],
       [3, 4, 9, 2],
       [7, 5, 8, 8]])

In [69]:
# np.random.randn() generates random numbers from the standard normal distribution,
# which has a mean of 0 and a standard deviation of 1.
# The values can be both positive and negative.
np.random.randn(3,3)

array([[ 1.18412742,  1.13889353,  1.5588243 ],
       [-0.5083255 , -0.77207305, -1.56015167],
       [ 1.78724316,  0.91571488,  0.73878261]])

In [70]:
# numpy.reshape()
# The reshape method is used to give a new shape to an array. 
# The new shape must be compatible with the original shape,
# meaning that the total number of elements must remain the same.
ary=np.fromstring("1,2,3,4,5,6,7,8,9,10,11,12", sep =",", dtype=int)
ary

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
ary.reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
ary.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
ary.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [74]:
ary.reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [75]:
ary.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [76]:
# size should be same
ary.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [77]:
ary.reshape(3,2,2,1,1,1)

array([[[[[[ 1]]],


         [[[ 2]]]],



        [[[[ 3]]],


         [[[ 4]]]]],




       [[[[[ 5]]],


         [[[ 6]]]],



        [[[[ 7]]],


         [[[ 8]]]]],




       [[[[[ 9]]],


         [[[10]]]],



        [[[[11]]],


         [[[12]]]]]])

In [78]:
ary1=np.random.randint(1,10, (4,5))

In [79]:
ary1

array([[7, 7, 6, 6, 1],
       [2, 4, 8, 5, 5],
       [4, 3, 6, 7, 5],
       [4, 2, 1, 3, 2]])

In [80]:
# to find or to perform opearation on array index-wise 

In [81]:
ary1 > 5

array([[ True,  True,  True,  True, False],
       [False, False,  True, False, False],
       [False, False,  True,  True, False],
       [False, False, False, False, False]])

In [82]:
ary1[ary1>5]

array([7, 7, 6, 6, 8, 6, 7])

In [83]:
# slicing an array
ary1

array([[7, 7, 6, 6, 1],
       [2, 4, 8, 5, 5],
       [4, 3, 6, 7, 5],
       [4, 2, 1, 3, 2]])

In [84]:
# row of ary1
ary1[0]

array([7, 7, 6, 6, 1])

In [85]:
# column of ary1 
# my_interpretation:- select each sub arr from 0 to 4 and get the '0th' element from each.
ary1[0:4,0]

array([7, 2, 4, 4])

In [86]:
ary1[1:4,2:5]

array([[8, 5, 5],
       [6, 7, 5],
       [1, 3, 2]])

In [87]:
ary1[1:3,[3,4]]

array([[5, 5],
       [7, 5]])

In [3]:
# BROADCASTING
# NumPy's broadcasting feature allows you to perform operations on arrays of different shapes

In [4]:
ar1=np.random.randint(1,20, (3,3))
ar2=np.random.randint(1,20, (3,3))

In [5]:
ar1

array([[13, 11,  3],
       [10, 15, 13],
       [ 8, 13, 19]])

In [6]:
ar2

array([[ 5,  9,  3],
       [11, 15,  6],
       [16, 15,  3]])

In [7]:
# observe additon,subtraction,multiplication(ordinary not matrix multiplication) is component-wise
ar1+ar2

array([[18, 20,  6],
       [21, 30, 19],
       [24, 28, 22]])

In [8]:
np.add(ar1,ar2)

array([[18, 20,  6],
       [21, 30, 19],
       [24, 28, 22]])

In [11]:
ar1-ar2

array([[ 8,  2,  0],
       [-1,  0,  7],
       [-8, -2, 16]])

In [12]:
np.subtract(ar1,ar2)

array([[ 8,  2,  0],
       [-1,  0,  7],
       [-8, -2, 16]])

In [13]:
ar1/ar2

array([[2.6       , 1.22222222, 1.        ],
       [0.90909091, 1.        , 2.16666667],
       [0.5       , 0.86666667, 6.33333333]])

In [14]:
np.divide(ar1,ar2)

array([[2.6       , 1.22222222, 1.        ],
       [0.90909091, 1.        , 2.16666667],
       [0.5       , 0.86666667, 6.33333333]])

In [15]:
# component-wise
ar1*ar2

array([[ 65,  99,   9],
       [110, 225,  78],
       [128, 195,  57]])

In [16]:
np.multiply(ar1,ar2)

array([[ 65,  99,   9],
       [110, 225,  78],
       [128, 195,  57]])

In [17]:
print(ar1," \n\n",ar2)

[[13 11  3]
 [10 15 13]
 [ 8 13 19]]  

 [[ 5  9  3]
 [11 15  6]
 [16 15  3]]


In [18]:
# to perform matrix multiplication, use '@'
ar1@ar2

array([[234, 327, 114],
       [423, 510, 159],
       [487, 552, 159]])

In [19]:
# to find mod component wise
np.mod(ar1,ar2)

array([[ 3,  2,  0],
       [10,  0,  1],
       [ 8, 13,  1]])

In [22]:
# to find power raised to 
np.power(ar1,ar2)

array([[            371293,         2357947691,                 27],
       [      100000000000, 437893890380859375,            4826809],
       [   281474976710656,  51185893014090757,               6859]])

In [21]:
np.power(ar1,2)

array([[169, 121,   9],
       [100, 225, 169],
       [ 64, 169, 361]])

In [23]:
# to find square-root 
np.sqrt(ar1)

array([[3.60555128, 3.31662479, 1.73205081],
       [3.16227766, 3.87298335, 3.60555128],
       [2.82842712, 3.60555128, 4.35889894]])

In [24]:
# more examples and Statistical function

In [25]:
ar3=np.ones((4,3), dtype=int)
ar3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
 ar3+5

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [27]:
ar3 * 5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [28]:
# to 'transpose' the matrix
ar3.T

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [29]:
ar4 = (ar3+35).T

In [30]:
ar4

array([[36, 36, 36, 36],
       [36, 36, 36, 36],
       [36, 36, 36, 36]])

In [31]:
np.sqrt(ar4)

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [32]:
np.sum(ar4)

432

In [33]:
np.mean(ar4)

36.0

In [34]:
np.exp(ar3)

array([[2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [35]:
np.log(ar4)

array([[3.58351894, 3.58351894, 3.58351894, 3.58351894],
       [3.58351894, 3.58351894, 3.58351894, 3.58351894],
       [3.58351894, 3.58351894, 3.58351894, 3.58351894]])

In [36]:
np.max(ar4)

36

In [37]:
np.min(ar4)

36

In [39]:
# standard deviation
np.std(ar4)

0.0

In [40]:
# media
np.median(ar4)

36.0

In [42]:
ar5=np.random.randint(1,5,(3,3))

In [44]:
# trigonometric functions
ar5

array([[3, 2, 1],
       [4, 1, 4],
       [4, 1, 2]])

In [45]:
np.sin(ar5)

array([[ 0.14112001,  0.90929743,  0.84147098],
       [-0.7568025 ,  0.84147098, -0.7568025 ],
       [-0.7568025 ,  0.84147098,  0.90929743]])

In [46]:
np.cos(ar5)

array([[-0.9899925 , -0.41614684,  0.54030231],
       [-0.65364362,  0.54030231, -0.65364362],
       [-0.65364362,  0.54030231, -0.41614684]])

In [47]:
 np.tan(ar5)

array([[-0.14254654, -2.18503986,  1.55740772],
       [ 1.15782128,  1.55740772,  1.15782128],
       [ 1.15782128,  1.55740772, -2.18503986]])

In [54]:
# numpy contains std log values like log2 log10 etc
np.log2(ar5)

array([[1.5849625, 1.       , 0.       ],
       [2.       , 0.       , 2.       ],
       [2.       , 0.       , 1.       ]])

In [55]:
np.exp(ar5)

array([[20.08553692,  7.3890561 ,  2.71828183],
       [54.59815003,  2.71828183, 54.59815003],
       [54.59815003,  2.71828183,  7.3890561 ]])

In [61]:
# to  flatten an array
print(ar5.flatten())
print("\n\n",ar5)

[3 2 1 4 1 4 4 1 2]


 [[3 2 1]
 [4 1 4]
 [4 1 2]]


In [64]:
np.expand_dims(ar5,axis=1)

array([[[3, 2, 1]],

       [[4, 1, 4]],

       [[4, 1, 2]]])

In [65]:
np.expand_dims(ar5,axis=2)

array([[[3],
        [2],
        [1]],

       [[4],
        [1],
        [4]],

       [[4],
        [1],
        [2]]])

In [67]:
ar6= np.array([[1],[2],[3]])

In [68]:
ar6

array([[1],
       [2],
       [3]])

In [69]:
np.squeeze(ar6)

array([1, 2, 3])

In [71]:
# each elemet will repeat n (=4) times
np.repeat(ar6,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [72]:
# to roll data through indexes 
np.roll(ar6,2)

array([[2],
       [3],
       [1]])

In [73]:
# to make a digonal matrix from a given arr
np.diag(ar6)

array([1])

In [74]:
np.diag(np.array([1,2,3,4,5]))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [76]:
ar5

array([[3, 2, 1],
       [4, 1, 4],
       [4, 1, 2]])

In [77]:
# to find binary negation of an array
~ar5

array([[-4, -3, -2],
       [-5, -2, -5],
       [-5, -2, -3]])

In [80]:
# Numpy string function

In [83]:
ar7= np.array(['tan','shar'])

In [84]:
ar7

array(['tan', 'shar'], dtype='<U4')

In [85]:
np.char.upper(ar7)

array(['TAN', 'SHAR'], dtype='<U4')

In [86]:
np.char.capitalize(ar7)

array(['Tan', 'Shar'], dtype='<U4')

In [87]:
np.char.title(ar7)

array(['Tan', 'Shar'], dtype='<U4')

In [88]:
arr1=np.array([78,47,0,12,46,82,89,32,12,90,47,56,33,28,12,0,89])

In [89]:
arr1

array([78, 47,  0, 12, 46, 82, 89, 32, 12, 90, 47, 56, 33, 28, 12,  0, 89])

In [92]:
arr1.sort()

In [93]:
arr1

array([ 0,  0, 12, 12, 12, 28, 32, 33, 46, 47, 47, 56, 78, 82, 89, 89, 90])

In [94]:
arr2=np.array([38,90,12,34,48,83,43,0,23,1,34,90,34,0,8,9])

In [102]:
# Signature: np.searchsorted(a, v, side='left', sorter=None)
# Docstring:
# Find indices where elements should be inserted to maintain order.
np.searchsorted(arr2,34)

10

In [103]:
np.count_nonzero(arr2)

14

In [104]:
np.where(arr2>89)

(array([ 1, 11]),)

In [105]:
# Numpy ByteSwapping

In [107]:
np.byte(arr2)

array([38, 90, 12, 34, 48, 83, 43,  0, 23,  1, 34, 90, 34,  0,  8,  9],
      dtype=int8)

In [110]:
arr2.byteswap()

array([2738188573441261568, 6485183463413514240,  864691128455135232,
       2449958197289549824, 3458764513820540928, 5980780305148018688,
       3098476543630901248,                   0, 1657324662872342528,
         72057594037927936, 2449958197289549824, 6485183463413514240,
       2449958197289549824,                   0,  576460752303423488,
        648518346341351424])

In [111]:
arr2

array([38, 90, 12, 34, 48, 83, 43,  0, 23,  1, 34, 90, 34,  0,  8,  9])

In [112]:
arr1

array([ 0,  0, 12, 12, 12, 28, 32, 33, 46, 47, 47, 56, 78, 82, 89, 89, 90])

In [115]:
# deep copy
x=np.copy(arr1)

In [116]:
x

array([ 0,  0, 12, 12, 12, 28, 32, 33, 46, 47, 47, 56, 78, 82, 89, 89, 90])

In [117]:
# solo-Copy
y=arr1.view()

In [118]:
y

array([ 0,  0, 12, 12, 12, 28, 32, 33, 46, 47, 47, 56, 78, 82, 89, 89, 90])

In [119]:
y[1]=8

In [121]:
# changes in y reflects in arr2
arr1

array([ 0,  8, 12, 12, 12, 28, 32, 33, 46, 47, 47, 56, 78, 82, 89, 89, 90])

In [122]:
y

array([ 0,  8, 12, 12, 12, 28, 32, 33, 46, 47, 47, 56, 78, 82, 89, 89, 90])

In [123]:
# NumPy Matrix Lib

In [124]:
import numpy.matlib as nm

In [128]:
mat1=nm.zeros(5)

In [129]:
type(mat1)

numpy.matrix

In [130]:
mat1

matrix([[0., 0., 0., 0., 0.]])

In [131]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [132]:
# Numpy- Linear Algebra

In [137]:
arr_l1=np.random.randint([[5,5],[5,5]])
arr_l2=np.random.randint([[3,3],[3,3]])

In [138]:
arr_l1

array([[1, 0],
       [1, 4]])

In [139]:
arr_l2

array([[2, 1],
       [0, 1]])

In [140]:
# to find dot product 
np.dot(arr_l1,arr_l2)

array([[2, 1],
       [2, 5]])

In [141]:
arr_l1 @ arr_l2

array([[2, 1],
       [2, 5]])